"""Build polished standalone HTML reports from Phase 0 and Phase 1a results."""

from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"


def img_tag(path: Path, alt: str = "", width: str = "100%") -> str:
    data = base64.b64encode(path.read_bytes()).decode()
    return f'<img src="data:image/png;base64,{data}" alt="{alt}" style="width:{width};max-width:900px;">'


CSS = """\
:root{--bg:#fafafa;--fg:#1a1a2e;--accent:#2d6a4f;--accent2:#40916c;--card:#fff;--border:#e0e0e0;--mono:\"JetBrains Mono\",\"Fira Code\",monospace;--sans:\"Inter\",\"Segoe UI\",system-ui,sans-serif}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:var(--sans);background:var(--bg);color:var(--fg);line-height:1.7;padding:2rem;max-width:960px;margin:0 auto}
h1{font-size:1.8rem;color:var(--accent);border-bottom:3px solid var(--accent);padding-bottom:.5rem;margin:1.5rem 0 1rem}
h2{font-size:1.35rem;color:var(--accent2);margin:2rem 0 .75rem;border-bottom:1px solid var(--border);padding-bottom:.3rem}
h3{font-size:1.1rem;color:var(--fg);margin:1.5rem 0 .5rem}
p{margin:.6rem 0}
table{width:100%;border-collapse:collapse;margin:1rem 0;font-size:.88rem}
th{background:var(--accent);color:#fff;padding:.55rem .7rem;text-align:left;font-weight:600}
td{padding:.45rem .7rem;border-bottom:1px solid var(--border)}
tr:nth-child(even){background:#f5f5f5}
.badge{display:inline-block;padding:.25rem .75rem;border-radius:4px;font-weight:700;font-size:.95rem;margin:.2rem .3rem}
.badge-go{background:#d4edda;color:#155724;border:1px solid #a3d9a5}
.badge-nogo{background:#f8d7da;color:#721c24;border:1px solid #f5c6cb}
.gate-box{background:var(--card);border:2px solid var(--accent);border-radius:8px;padding:1.2rem 1.5rem;margin:1.5rem 0;box-shadow:0 2px 8px rgba(0,0,0,.06)}
.figure{margin:1.5rem 0;text-align:center}
.figure img{border:1px solid var(--border);border-radius:6px;box-shadow:0 2px 12px rgba(0,0,0,.08)}
.figure figcaption{font-size:.85rem;color:#555;margin-top:.4rem;font-style:italic}
.finding{background:#fff;border-left:4px solid var(--accent2);padding:.8rem 1.2rem;margin:.8rem 0;border-radius:0 6px 6px 0}
.finding strong{color:var(--accent)}
code{font-family:var(--mono);background:#eee;padding:.1rem .35rem;border-radius:3px;font-size:.87rem}
.footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--border);font-size:.8rem;color:#888;text-align:center}
"""


def build_phase0():
    g0 = img_tag(RESULTS / "phase0/g0_summary.png", "G0 Gate Summary")
    profiles = img_tag(RESULTS / "phase0/spectral_profiles.png", "Spectral Energy Profiles")
    decay = img_tag(RESULTS / "phase0/energy_decay.png", "Energy Decay")

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Graph-FANS Phase 0 Report</title>
<style>{CSS}</style></head>
<body>

<h1>Phase 0: Empirical Spectral Profiling</h1>

<div class="gate-box">
  <strong>Gate G0</strong> &mdash; Energy ratio between lowest and highest band &ge;2&times; for &ge;2 graph families<br>
  <span class="badge badge-go">DECISION: GO</span> &mdash; 9/9 families pass (ratios 3.8&times;&ndash;17.0&times;)
</div>

<h2>Method</h2>
<p>For each graph family we computed the normalized Laplacian eigendecomposition, partitioned eigenvalues into <em>B&nbsp;=&nbsp;8</em> uniform-width bands on [0,&nbsp;&lambda;<sub>max</sub>], projected node features onto eigenvectors per band, and measured squared-coefficient energy. We fit power-law and exponential decay models and averaged over 3 random seeds for synthetic graphs.</p>
<p>Node features for synthetic graphs were generated by low-pass filtering random signals through exp(&minus;tL) to produce realistic smooth graph signals.</p>

<h2>Graph Families</h2>
<table>
<tr><th>Family</th><th>Type</th><th>Parameters</th></tr>
<tr><td>SBM (4 configs)</td><td>Stochastic Block Model</td><td>n=200, 4 communities, p<sub>intra</sub>=0.3, q&isin;&#123;0.01, 0.05, 0.1, 0.2&#125;</td></tr>
<tr><td>BA (3 configs)</td><td>Barab&aacute;si-Albert</td><td>n=200, m&isin;&#123;2, 5, 10&#125;</td></tr>
<tr><td>Cora</td><td>Citation network</td><td>n=2708, real features</td></tr>
<tr><td>CiteSeer</td><td>Citation network</td><td>n=3327, real features</td></tr>
</table>

<h2>Results</h2>

<table>
<tr><th>Graph Family</th><th>Energy Ratio</th><th>Decay Model</th><th>R&sup2;</th><th>G0</th></tr>
<tr><td>SBM(q=0.01)</td><td>3.8&times;</td><td>power_law</td><td>0.12</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>SBM(q=0.05)</td><td>6.9&times;</td><td>power_law</td><td>0.35</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>SBM(q=0.1)</td><td>10.7&times;</td><td>power_law</td><td>0.44</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>SBM(q=0.2)</td><td>8.3&times;</td><td>power_law</td><td>0.51</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>BA(m=2)</td><td><strong>17.0&times;</strong></td><td>exponential</td><td>0.39</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>BA(m=5)</td><td>8.1&times;</td><td>power_law</td><td>0.05</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>BA(m=10)</td><td>6.7&times;</td><td>power_law</td><td>0.30</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>Cora</td><td>4.0&times;</td><td>power_law</td><td>0.49</td><td><span class="badge badge-go">PASS</span></td></tr>
<tr><td>CiteSeer</td><td>5.0&times;</td><td>power_law</td><td>0.39</td><td><span class="badge badge-go">PASS</span></td></tr>
</table>

<figure class="figure">{g0}<figcaption>G0 gate summary: energy ratios and decay fit quality across all families</figcaption></figure>

<figure class="figure">{profiles}<figcaption>Per-band spectral energy profiles for all 9 graph families (B=8 bands)</figcaption></figure>

<figure class="figure">{decay}<figcaption>Normalized band energy curves overlaid across graph families</figcaption></figure>

<h2>Key Findings</h2>

<div class="finding">
<strong>1. Non-uniformity is universal and strong.</strong>
Every tested graph family shows energy ratios well above the 2&times; threshold. The effect is strongest for BA(m=2) at 17&times; and weakest for SBM(q=0.01) at 3.8&times;. This conclusively supports the premise that graph signal energy is non-uniformly distributed across spectral bands.
</div>

<div class="finding">
<strong>2. Graphs do NOT follow a simple 1/f decay.</strong>
Unlike images (where FANS exploits a ~1/f spectral decay), graph spectral energy profiles show complex, family-specific patterns. SBM energy concentrates in low-to-mid bands with peaks shifting as modularity increases. BA(m=2) shows exponential decay consistent with tree-like structure, while higher-m variants are flatter. Citation networks show moderate power-law decay with energy spread across all bands. A blanket inverse-power weighting scheme is suboptimal &mdash; weighting must be <em>data-driven and family-specific</em>.
</div>

<div class="finding">
<strong>3. Low R&sup2; values indicate complex structure.</strong>
Decay model fits have low R&sup2; (0.05&ndash;0.51), confirming spectral energy is not well-described by simple parametric decay. Profiles are hump-shaped, bimodal, or irregularly distributed. This argues for per-family empirical profiling rather than assumed functional forms.
</div>

<h2>Implications for Graph-FANS</h2>
<ol style="margin:1rem 0;padding-left:1.5rem">
<li>Importance profiling must be <strong>empirical</strong>, computed per training distribution</li>
<li>The inverse-power weighting from FANS should be replaced with <strong>direct importance weighting</strong> from measured band energies</li>
<li>Band count <strong>B=8</strong> captures sufficient spectral resolution</li>
<li>Different graph families need <strong>different noise schedules</strong></li>
</ol>

<div class="footer">Graph-FANS &middot; Phase 0 Report &middot; 2026-03-22 &middot; <code>~/projects/graph-fans/results/phase0/</code></div>
</body></html>"""

    out = RESULTS / "phase0" / "report.html"
    out.write_text(html)
    print(f"  Written: {out}")


def build_phase1a():
    g1 = img_tag(RESULTS / "phase1a/g1_summary.png", "G1 Gate Summary")
    comparison = img_tag(RESULTS / "phase1a/metric_comparison.png", "Metric Comparison")
    gap = img_tag(RESULTS / "phase1a/information_gap.png", "Information Gap")
    sd0 = img_tag(RESULTS / "phase1a/spectral_density_0.png", "Spectral Density 0")
    sd1 = img_tag(RESULTS / "phase1a/spectral_density_1.png", "Spectral Density 1")
    hks0 = img_tag(RESULTS / "phase1a/hks_0.png", "HKS 0")
    hks1 = img_tag(RESULTS / "phase1a/hks_1.png", "HKS 1")

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Graph-FANS Phase 1a Report</title>
<style>{CSS}</style></head>
<body>

<h1>Phase 1a: Basis-Free Spectral Metrics</h1>

<div class="gate-box">
  <strong>Gate G1</strong> &mdash; At least 1 of 3 proposed metrics shows &ge;10% relative difference from aggregate MMD<br>
  <span class="badge badge-go">DECISION: GO</span> &mdash; All 12/12 pairs exceed 10%; up to 63&times; relative gap
</div>

<h2>Metrics Implemented</h2>

<h3>Spectral Metrics (proposed)</h3>
<table>
<tr><th>Metric</th><th>Definition</th><th>Sensitivity</th></tr>
<tr><td><strong>Spectral Density JSD</strong></td><td>KDE on normalized eigenvalues &lambda;<sub>i</sub>/&lambda;<sub>max</sub>, Jensen-Shannon divergence</td><td>Coarse-grained spectral shape</td></tr>
<tr><td><strong>Quantile-Band Energy (QBE)</strong></td><td>Equal-mass quantile bands, L2 distance between normalized per-band energy</td><td>Fine-grained spectral fidelity</td></tr>
<tr><td><strong>Heat Kernel Signature (HKS)</strong></td><td>Tr(exp(&minus;tL)) over 50 log-spaced t, L2 distance of normalized traces</td><td>Multi-scale diffusion structure</td></tr>
</table>

<h3>Standard Metrics (baseline comparison)</h3>
<table>
<tr><th>Metric</th><th>Definition</th></tr>
<tr><td>Degree MMD</td><td>MMD with RBF kernel on degree distributions</td></tr>
<tr><td>Clustering MMD</td><td>MMD on local clustering coefficient distributions</td></tr>
<tr><td>Triangle MMD</td><td>MMD on per-node triangle count distributions</td></tr>
</table>

<h2>Experimental Design</h2>
<p><strong>Reference graphs:</strong> SBM(q=0.01), SBM(q=0.1), BA(m=3), BA(m=8)</p>
<p><strong>Baselines</strong> (3 types of decreasing spectral fidelity):</p>
<ul style="margin:.5rem 0;padding-left:1.5rem">
<li><strong>ER (matched density)</strong> &mdash; Erd&#337;s-R&eacute;nyi with same edge density. Poor spectral match.</li>
<li><strong>Configuration model (matched degree)</strong> &mdash; Same degree sequence. Good local structure, wrong spectral structure.</li>
<li><strong>SBM (approx params)</strong> &mdash; SBM with heuristically matched parameters. Moderate match.</li>
</ul>
<p>Total: <strong>12 reference-baseline pairs</strong>.</p>

<h2>Results</h2>

<figure class="figure">{g1}<figcaption>G1 gate: metrics heatmap and spectral information gap</figcaption></figure>

<figure class="figure">{comparison}<figcaption>Standard vs spectral metrics across all 12 pairs</figcaption></figure>

<h3>Full Metrics Table</h3>
<table>
<tr><th>Reference</th><th>Baseline</th><th>Spec. JSD</th><th>QBE</th><th>HKS</th><th>Deg MMD</th><th>Clust MMD</th><th>Tri MMD</th></tr>
<tr><td>SBM(q=0.01)</td><td>ER</td><td>0.012</td><td>0.189</td><td>0.017</td><td>0.011</td><td>0.057</td><td>0.322</td></tr>
<tr><td>SBM(q=0.01)</td><td>Config</td><td>0.013</td><td>0.185</td><td>0.016</td><td>0.006</td><td>0.056</td><td>0.319</td></tr>
<tr><td>SBM(q=0.01)</td><td>SBM</td><td>0.048</td><td>0.185</td><td>0.021</td><td>0.242</td><td>0.024</td><td>0.154</td></tr>
<tr><td>SBM(q=0.1)</td><td>ER</td><td>0.001</td><td>0.123</td><td>0.001</td><td>0.010</td><td>0.000</td><td>0.009</td></tr>
<tr><td>SBM(q=0.1)</td><td>Config</td><td>0.002</td><td>0.153</td><td>0.002</td><td>0.024</td><td>0.001</td><td>0.053</td></tr>
<tr><td>SBM(q=0.1)</td><td>SBM</td><td>0.217</td><td>0.139</td><td>0.010</td><td>0.277</td><td>0.489</td><td>0.102</td></tr>
<tr><td>BA(m=3)</td><td>ER</td><td>0.002</td><td>0.251</td><td>0.042</td><td>0.117</td><td>0.007</td><td>0.023</td></tr>
<tr><td>BA(m=3)</td><td>Config</td><td>0.001</td><td><strong>0.260</strong></td><td>0.017</td><td>0.001</td><td>0.001</td><td>0.010</td></tr>
<tr><td>BA(m=3)</td><td>SBM</td><td>0.018</td><td>0.244</td><td>0.038</td><td>0.375</td><td>0.003</td><td>0.470</td></tr>
<tr><td>BA(m=8)</td><td>ER</td><td>0.000</td><td>0.193</td><td>0.003</td><td>0.117</td><td>0.017</td><td>0.044</td></tr>
<tr><td>BA(m=8)</td><td>Config</td><td>0.001</td><td>0.199</td><td>0.005</td><td>0.004</td><td>0.003</td><td>0.029</td></tr>
<tr><td>BA(m=8)</td><td>SBM</td><td>0.072</td><td>0.199</td><td>0.014</td><td>0.244</td><td>0.063</td><td>0.230</td></tr>
</table>

<h3>Information Gap Analysis</h3>

<figure class="figure">{gap}<figcaption>Spectral aggregate vs standard aggregate &mdash; points above the diagonal indicate spectral metrics detect more degradation</figcaption></figure>

<table>
<tr><th>Pair</th><th>Max Gap</th><th>Dominant Metric</th></tr>
<tr><td>BA(m=3) vs Config</td><td><strong>63&times;</strong></td><td>QBE Distance</td></tr>
<tr><td>SBM(q=0.1) vs ER</td><td>18.5&times;</td><td>QBE Distance</td></tr>
<tr><td>BA(m=8) vs Config</td><td>15.9&times;</td><td>QBE Distance</td></tr>
<tr><td>BA(m=3) vs ER</td><td>4.1&times;</td><td>QBE Distance</td></tr>
<tr><td>BA(m=8) vs ER</td><td>2.2&times;</td><td>QBE Distance</td></tr>
</table>

<p><strong>Rank correlation:</strong> Spearman &rho; = 0.64, p = 0.024 &mdash; statistically significant but moderate, confirming the two metric families capture partially independent information.</p>

<h3>Spectral Density &amp; HKS Comparisons</h3>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1rem 0">
<figure class="figure">{sd0}<figcaption>Spectral density: SBM(q=0.01) vs ER</figcaption></figure>
<figure class="figure">{sd1}<figcaption>Spectral density: SBM(q=0.01) vs Config</figcaption></figure>
<figure class="figure">{hks0}<figcaption>HKS traces: SBM(q=0.01) vs ER</figcaption></figure>
<figure class="figure">{hks1}<figcaption>HKS traces: SBM(q=0.01) vs Config</figcaption></figure>
</div>

<h2>Key Findings</h2>

<div class="finding">
<strong>1. QBE is the most informative new metric.</strong>
Quantile-band energy distance consistently produces the largest information gap across all 12 pairs. The clearest case: BA(m=3) vs Configuration model &mdash; degree MMD is 0.001 (essentially identical), but QBE distance is 0.260 (63&times; relative gap). The configuration model preserves degree structure but completely fails to reproduce spectral energy distribution.
</div>

<div class="finding">
<strong>2. Spectral JSD is less sensitive at small scales.</strong>
JSD shows meaningful separation only for large structural differences (SBM vs SBM mismatch). For subtle differences (ER, config model), JSD values are very small (&lt;0.02) because KDE smoothing loses resolution for localized spectral differences.
</div>

<div class="finding">
<strong>3. HKS provides complementary signal.</strong>
HKS distance captures differences at specific diffusion timescales, most informative for SBM pairs where community structure creates characteristic timescale signatures.
</div>

<div class="finding">
<strong>4. Standard metrics have blind spots.</strong>
The configuration model baseline exposes a fundamental blind spot: graphs with identical degree sequences can have vastly different spectral properties. Standard degree/clustering/orbit MMD cannot detect this &mdash; validating the core premise of H3.
</div>

<h2>Evaluation Strategy for Phase 2</h2>
<ol style="margin:1rem 0;padding-left:1.5rem">
<li><strong>QBE distance</strong> as primary spectral fidelity metric</li>
<li><strong>HKS distance</strong> as complementary multi-scale metric</li>
<li><strong>Spectral JSD</strong> for coarse-grained sanity checks</li>
<li><strong>Standard MMD</strong> metrics reported for comparability with prior work</li>
</ol>

<div class="footer">Graph-FANS &middot; Phase 1a Report &middot; 2026-03-22 &middot; <code>~/projects/graph-fans/results/phase1a/</code></div>
</body></html>"""

    out = RESULTS / "phase1a" / "report.html"
    out.write_text(html)
    print(f"  Written: {out}")


if __name__ == "__main__":
    print("Building HTML reports...")
    build_phase0()
    build_phase1a()
    print("Done.")
